import type { Language } from "./i18n";
import type { MacModel } from "./product-data";
import type { ProductCopy } from "./product-copy-types";

const macProductCopy: Record<Language, Record<MacModel, ProductCopy>> = {
  en: {
    "macbook-air-m5": {
      name: "MacBook Air",
      eyebrow: "SUPERCHARGED BY M5.",
      intro: "A remarkably light 13- or 15-inch laptop with M5, up to 18 hours of battery life, and a 12MP Center Stage camera.",
      display: "13.6″ / 15.3″",
      camera: "12MP Center Stage",
      battery: "18 hours",
      designTitle: "Two sizes. Effortlessly portable.",
      designBody: "The thin aluminum enclosure comes in four finishes, with MagSafe, two Thunderbolt 4 ports, and a silent fanless design.",
      cameraTitle: "Liquid Retina. Camera ready.",
      cameraBody: "The bright P3 Liquid Retina display pairs with a 12MP Center Stage camera, Desk View, a three-mic array, and immersive speakers.",
      secondarySectionKicker: "DISPLAY / 02",
      performanceTitle: "M5 makes light work of it.",
      performanceBody: "M5 accelerates everyday work, creative apps, graphics, and on-device AI while supporting two external displays and all-day battery life.",
    },
    "macbook-pro-m5": {
      name: "MacBook Pro",
      eyebrow: "PRO POWER. BUILT FOR AI.",
      intro: "M5, M5 Pro, or M5 Max performance, a Liquid Retina XDR display, and up to 24 hours of battery life in 14- and 16-inch designs.",
      display: "14.2″ / 16.2″ XDR",
      camera: "12MP Center Stage",
      battery: "24 hours",
      designTitle: "A portable studio in two sizes.",
      designBody: "A durable aluminum enclosure integrates MagSafe 3, HDMI, SDXC, a headphone jack, and three Thunderbolt ports for serious workflows.",
      cameraTitle: "XDR range. Center Stage clarity.",
      cameraBody: "Liquid Retina XDR brings extreme dynamic range and ProMotion, while the 12MP Center Stage camera adds Desk View and sharper calls.",
      secondarySectionKicker: "DISPLAY / 02",
      performanceTitle: "Choose M5, M5 Pro, or M5 Max.",
      performanceBody: "Apple silicon combines high-performance CPU and GPU cores, hardware ray tracing, Neural Accelerators, and dedicated media engines for demanding pro work.",
    },
    "imac-m4": {
      name: "iMac",
      eyebrow: "BRILLIANT ALL-IN-ONE.",
      intro: "M4, a 24-inch 4.5K Retina display, a 12MP Center Stage camera, and room-filling audio in an exceptionally thin design.",
      display: "24″ 4.5K Retina",
      camera: "12MP Center Stage",
      battery: "Wall power",
      designTitle: "Everything in one vivid silhouette.",
      designBody: "At just 11.5 millimeters thin, iMac brings the computer and display together in seven colors with color-matched accessories.",
      cameraTitle: "A canvas for every detail.",
      cameraBody: "The 4.5K Retina display delivers 4480-by-2520 resolution and P3 color, joined by a Center Stage camera, studio-quality mics, and a six-speaker system.",
      secondarySectionKicker: "DISPLAY / 02",
      performanceTitle: "M4 transforms the all-in-one.",
      performanceBody: "A fast CPU, GPU, and Neural Engine power creation, gaming, multitasking, and Apple Intelligence with up to 32GB of unified memory.",
    },
    "mac-mini-m6": {
      name: "Mac mini",
      eyebrow: "MIGHTY. MINI.",
      intro: "The ultracompact desktop now brings M6 or M5 Pro performance, a powerful platform for AI, and practical ports front and back.",
      display: "M6 / M5 Pro",
      primarySpecLabel: "CHIP",
      camera: "Up to 3",
      secondarySpecLabel: "DISPLAYS",
      battery: "Wall power",
      designTitle: "Five by five inches of possibility.",
      designBody: "The compact aluminum enclosure puts USB-C and audio within reach up front, with Thunderbolt, HDMI, Ethernet, and power neatly arranged behind.",
      cameraTitle: "A flexible center for your setup.",
      cameraBody: "Connect high-resolution displays, fast storage, networks, and accessories through a versatile mix of front and rear ports.",
      secondarySectionKicker: "CONNECTIVITY / 02",
      performanceTitle: "M6 speed. M5 Pro scale.",
      performanceBody: "Choose M6 for fast everyday and AI work, or M5 Pro for heavier code, media, and graphics workflows in the same tiny footprint.",
    },
    "mac-studio-m5": {
      name: "Mac Studio",
      eyebrow: "THE ULTIMATE PRO DESKTOP.",
      intro: "M5 Max or M5 Ultra performance, exceptional connectivity, and powerful on-device AI in a compact desktop enclosure.",
      display: "M5 Max / Ultra",
      primarySpecLabel: "CHIP",
      camera: "Up to 8",
      secondarySpecLabel: "DISPLAYS",
      battery: "Wall power",
      designTitle: "Studio power. Desk-friendly form.",
      designBody: "A compact aluminum body uses an advanced thermal system to sustain huge workloads while remaining quiet beneath most displays.",
      cameraTitle: "A studio of connections.",
      cameraBody: "Thunderbolt 5, HDMI, 10Gb Ethernet, USB, audio, and an SDXC slot connect displays, storage, capture hardware, and fast networks.",
      secondarySectionKicker: "CONNECTIVITY / 02",
      performanceTitle: "M5 Max. M5 Ultra. No small ambition.",
      performanceBody: "High-bandwidth unified memory, powerful graphics, Neural Accelerators, and media engines tackle large AI models, 3D scenes, and professional video.",
    },
    "mac-pro-m2-ultra": {
      name: "Mac Pro",
      eyebrow: "APPLE SILICON. PCIe EXPANSION.",
      intro: "The final Mac Pro pairs M2 Ultra with seven expansion slots for specialized workstation workflows in an iconic stainless-steel frame.",
      display: "M2 Ultra",
      primarySpecLabel: "CHIP",
      camera: "7 slots",
      secondarySpecLabel: "PCIE",
      battery: "Wall power",
      designTitle: "Built to change with the workflow.",
      designBody: "The removable aluminum housing and stainless-steel space frame provide 360-degree access, optional wheels, and room for specialized hardware.",
      cameraTitle: "Expansion is part of the architecture.",
      cameraBody: "Seven slots, six of them PCIe Gen 4, add audio and video I/O, networking, and storage alongside extensive Thunderbolt connectivity.",
      secondarySectionKicker: "EXPANSION / 02",
      performanceTitle: "M2 Ultra at workstation scale.",
      performanceBody: "A 24-core CPU, up to 76-core GPU, 32-core Neural Engine, and up to 192GB of unified memory drive demanding 3D, AI, and 8K ProRes workflows.",
    },
  },
  vi: {
    "macbook-air-m5": {
      name: "MacBook Air", eyebrow: "ĐƯỢC TIẾP SỨC MẠNH BỞI M5.", intro: "Laptop 13 hoặc 15 inch nhẹ ấn tượng với M5, thời lượng pin lên đến 18 giờ và camera 12MP Center Stage.", display: "13,6″ / 15,3″", camera: "12MP Center Stage", battery: "18 giờ", designTitle: "Hai kích thước. Nhẹ nhàng cơ động.", designBody: "Vỏ nhôm mỏng có bốn màu, MagSafe, hai cổng Thunderbolt 4 và thiết kế không quạt hoàn toàn yên tĩnh.", cameraTitle: "Liquid Retina. Luôn sẵn sàng lên hình.", cameraBody: "Màn hình Liquid Retina dải màu P3 kết hợp camera 12MP Center Stage, Desk View, cụm ba mic và hệ thống loa sống động.", secondarySectionKicker: "MÀN HÌNH / 02", performanceTitle: "M5 xử lý nhẹ tênh.", performanceBody: "M5 tăng tốc công việc, sáng tạo, đồ họa và AI trên thiết bị, đồng thời hỗ trợ hai màn hình ngoài và thời lượng pin cả ngày.",
    },
    "macbook-pro-m5": {
      name: "MacBook Pro", eyebrow: "SỨC MẠNH PRO. SINH RA CHO AI.", intro: "Hiệu năng M5, M5 Pro hoặc M5 Max, màn hình Liquid Retina XDR và pin lên đến 24 giờ trong thiết kế 14 và 16 inch.", display: "14,2″ / 16,2″ XDR", camera: "12MP Center Stage", battery: "24 giờ", designTitle: "Studio di động với hai kích thước.", designBody: "Vỏ nhôm bền bỉ tích hợp MagSafe 3, HDMI, SDXC, jack tai nghe và ba cổng Thunderbolt cho quy trình chuyên nghiệp.", cameraTitle: "Dải tương phản XDR. Center Stage rõ nét.", cameraBody: "Liquid Retina XDR mang đến dải tương phản cực rộng và ProMotion, còn camera 12MP Center Stage bổ sung Desk View và cuộc gọi sắc nét hơn.", secondarySectionKicker: "MÀN HÌNH / 02", performanceTitle: "Chọn M5, M5 Pro hoặc M5 Max.", performanceBody: "Apple silicon kết hợp CPU và GPU hiệu năng cao, ray tracing phần cứng, Neural Accelerator và media engine chuyên dụng cho công việc chuyên sâu.",
    },
    "imac-m4": {
      name: "iMac", eyebrow: "ALL-IN-ONE RỰC RỠ.", intro: "M4, màn hình Retina 4.5K 24 inch, camera 12MP Center Stage và âm thanh phủ đầy căn phòng trong thiết kế siêu mỏng.", display: "24″ Retina 4.5K", camera: "12MP Center Stage", battery: "Nguồn điện", designTitle: "Tất cả trong một dáng hình rực rỡ.", designBody: "Chỉ mỏng 11,5 mm, iMac gộp máy tính và màn hình trong bảy màu cùng phụ kiện đồng màu.", cameraTitle: "Không gian cho từng chi tiết.", cameraBody: "Màn hình Retina 4.5K có độ phân giải 4480 × 2520 và dải màu P3, đi cùng camera Center Stage, mic chuẩn studio và hệ thống sáu loa.", secondarySectionKicker: "MÀN HÌNH / 02", performanceTitle: "M4 biến đổi máy tính all-in-one.", performanceBody: "CPU, GPU và Neural Engine nhanh xử lý sáng tạo, chơi game, đa nhiệm và Apple Intelligence với bộ nhớ thống nhất lên đến 32GB.",
    },
    "mac-mini-m6": {
      name: "Mac mini", eyebrow: "NHỎ MÀ CÓ VÕ.", intro: "Máy tính để bàn siêu nhỏ gọn với M6 hoặc M5 Pro, nền tảng AI mạnh mẽ và hệ cổng tiện dụng ở cả mặt trước lẫn sau.", display: "M6 / M5 Pro", primarySpecLabel: "CHIP", camera: "Tối đa 3", secondarySpecLabel: "MÀN HÌNH", battery: "Nguồn điện", designTitle: "12,7 cm vuông đầy tiềm năng.", designBody: "Vỏ nhôm nhỏ gọn đặt USB-C và âm thanh ở phía trước; Thunderbolt, HDMI, Ethernet và nguồn điện được bố trí gọn phía sau.", cameraTitle: "Trung tâm linh hoạt cho mọi thiết lập.", cameraBody: "Kết nối màn hình độ phân giải cao, bộ nhớ tốc độ cao, mạng và phụ kiện qua hệ cổng đa dạng ở mặt trước và sau.", secondarySectionKicker: "KẾT NỐI / 02", performanceTitle: "Tốc độ M6. Quy mô M5 Pro.", performanceBody: "Chọn M6 cho công việc thường ngày và AI tốc độ cao, hoặc M5 Pro cho lập trình, media và đồ họa nặng hơn trong cùng kích thước nhỏ gọn.",
    },
    "mac-studio-m5": {
      name: "Mac Studio", eyebrow: "MÁY TÍNH PRO ĐỂ BÀN ĐỈNH CAO.", intro: "Hiệu năng M5 Max hoặc M5 Ultra, kết nối vượt trội và AI mạnh mẽ trên thiết bị trong một thân máy nhỏ gọn.", display: "M5 Max / Ultra", primarySpecLabel: "CHIP", camera: "Tối đa 8", secondarySpecLabel: "MÀN HÌNH", battery: "Nguồn điện", designTitle: "Sức mạnh studio. Vừa vặn bàn làm việc.", designBody: "Thân nhôm nhỏ gọn dùng hệ thống tản nhiệt tiên tiến để duy trì khối lượng công việc lớn mà vẫn yên tĩnh dưới hầu hết màn hình.", cameraTitle: "Cả studio kết nối trong tầm tay.", cameraBody: "Thunderbolt 5, HDMI, Ethernet 10Gb, USB, âm thanh và khe SDXC kết nối màn hình, bộ nhớ, thiết bị ghi hình và mạng tốc độ cao.", secondarySectionKicker: "KẾT NỐI / 02", performanceTitle: "M5 Max. M5 Ultra. Tham vọng không nhỏ.", performanceBody: "Bộ nhớ thống nhất băng thông cao, đồ họa mạnh, Neural Accelerator và media engine xử lý mô hình AI lớn, cảnh 3D và video chuyên nghiệp.",
    },
    "mac-pro-m2-ultra": {
      name: "Mac Pro", eyebrow: "APPLE SILICON. KHẢ NĂNG MỞ RỘNG PCIE.", intro: "Mac Pro cuối cùng kết hợp M2 Ultra với bảy khe mở rộng cho quy trình workstation chuyên biệt trong khung thép không gỉ biểu tượng.", display: "M2 Ultra", primarySpecLabel: "CHIP", camera: "7 khe", secondarySpecLabel: "PCIE", battery: "Nguồn điện", designTitle: "Sẵn sàng thay đổi theo công việc.", designBody: "Vỏ nhôm tháo rời và khung thép không gỉ cho phép tiếp cận 360 độ, tùy chọn bánh xe và không gian cho phần cứng chuyên dụng.", cameraTitle: "Khả năng mở rộng nằm trong kiến trúc.", cameraBody: "Bảy khe, trong đó sáu khe PCIe Gen 4, bổ sung I/O âm thanh và video, mạng và lưu trữ bên cạnh hệ cổng Thunderbolt phong phú.", secondarySectionKicker: "MỞ RỘNG / 02", performanceTitle: "M2 Ultra ở quy mô workstation.", performanceBody: "CPU 24 lõi, GPU lên đến 76 lõi, Neural Engine 32 lõi và bộ nhớ thống nhất lên đến 192GB vận hành 3D, AI và 8K ProRes chuyên sâu.",
    },
  },
  pt: {
    "macbook-air-m5": { name: "MacBook Air", eyebrow: "SUPERPOTENCIADO PELO M5.", intro: "Portátil de 13 ou 15 polegadas incrivelmente leve, com M5, até 18 horas de bateria e câmara Center Stage de 12 MP.", display: "13,6″ / 15,3″", camera: "Center Stage 12 MP", battery: "18 horas", designTitle: "Dois tamanhos. Mobilidade sem esforço.", designBody: "A estrutura fina de alumínio oferece quatro acabamentos, MagSafe, duas portas Thunderbolt 4 e funcionamento silencioso sem ventoinha.", cameraTitle: "Liquid Retina. Sempre pronto para a câmara.", cameraBody: "O ecrã Liquid Retina P3 junta-se à câmara Center Stage de 12 MP, Vista de Secretária, três microfones e colunas envolventes.", secondarySectionKicker: "ECRÃ / 02", performanceTitle: "M5 torna tudo mais leve.", performanceBody: "O M5 acelera trabalho, criação, gráficos e IA no dispositivo, com suporte para dois monitores externos e bateria para todo o dia." },
    "macbook-pro-m5": { name: "MacBook Pro", eyebrow: "POTÊNCIA PRO. FEITO PARA IA.", intro: "M5, M5 Pro ou M5 Max, ecrã Liquid Retina XDR e até 24 horas de bateria em formatos de 14 e 16 polegadas.", display: "14,2″ / 16,2″ XDR", camera: "Center Stage 12 MP", battery: "24 horas", designTitle: "Um estúdio portátil em dois tamanhos.", designBody: "A estrutura de alumínio integra MagSafe 3, HDMI, SDXC, áudio e três portas Thunderbolt para fluxos profissionais.", cameraTitle: "Amplitude XDR. Clareza Center Stage.", cameraBody: "Liquid Retina XDR oferece alcance dinâmico extremo e ProMotion; a câmara Center Stage de 12 MP acrescenta Vista de Secretária e chamadas mais nítidas.", secondarySectionKicker: "ECRÃ / 02", performanceTitle: "Escolha M5, M5 Pro ou M5 Max.", performanceBody: "CPU e GPU potentes, ray tracing por hardware, aceleradores neurais e motores multimédia dedicados enfrentam trabalho profissional exigente." },
    "imac-m4": { name: "iMac", eyebrow: "UM TUDO-EM-UM BRILHANTE.", intro: "M4, ecrã Retina 4.5K de 24 polegadas, câmara Center Stage de 12 MP e áudio amplo num design excecionalmente fino.", display: "24″ Retina 4.5K", camera: "Center Stage 12 MP", battery: "Rede elétrica", designTitle: "Tudo numa silhueta vibrante.", designBody: "Com apenas 11,5 mm, o iMac reúne computador e ecrã em sete cores com acessórios a condizer.", cameraTitle: "Uma tela para cada detalhe.", cameraBody: "O ecrã Retina 4.5K tem resolução 4480 × 2520 e cor P3, acompanhado por Center Stage, microfones de estúdio e seis colunas.", secondarySectionKicker: "ECRÃ / 02", performanceTitle: "M4 transforma o tudo-em-um.", performanceBody: "CPU, GPU e Neural Engine rápidos impulsionam criação, jogos, multitarefa e Apple Intelligence com até 32 GB de memória unificada." },
    "mac-mini-m6": { name: "Mac mini", eyebrow: "PEQUENO. PODEROSO.", intro: "Desktop ultracompacto com M6 ou M5 Pro, uma plataforma potente para IA e portas práticas à frente e atrás.", display: "M6 / M5 Pro", primarySpecLabel: "CHIP", camera: "Até 3", secondarySpecLabel: "MONITORES", battery: "Rede elétrica", designTitle: "12,7 centímetros de possibilidades.", designBody: "A caixa de alumínio coloca USB-C e áudio à frente, com Thunderbolt, HDMI, Ethernet e alimentação organizados atrás.", cameraTitle: "Centro flexível para o seu espaço.", cameraBody: "Ligue monitores de alta resolução, armazenamento rápido, redes e acessórios através das portas frontais e traseiras.", secondarySectionKicker: "LIGAÇÕES / 02", performanceTitle: "Velocidade M6. Escala M5 Pro.", performanceBody: "Escolha M6 para tarefas e IA rápidas ou M5 Pro para código, multimédia e gráficos mais exigentes no mesmo formato mínimo." },
    "mac-studio-m5": { name: "Mac Studio", eyebrow: "O DESKTOP PRO DEFINITIVO.", intro: "M5 Max ou M5 Ultra, ligações excecionais e IA potente no dispositivo numa estrutura compacta.", display: "M5 Max / Ultra", primarySpecLabel: "CHIP", camera: "Até 8", secondarySpecLabel: "MONITORES", battery: "Rede elétrica", designTitle: "Potência de estúdio. Formato de secretária.", designBody: "A caixa de alumínio compacta usa refrigeração avançada para sustentar cargas enormes em silêncio.", cameraTitle: "Um estúdio de ligações.", cameraBody: "Thunderbolt 5, HDMI, Ethernet 10 Gb, USB, áudio e SDXC ligam monitores, armazenamento, captura e redes rápidas.", secondarySectionKicker: "LIGAÇÕES / 02", performanceTitle: "M5 Max. M5 Ultra. Ambição enorme.", performanceBody: "Memória unificada de alta largura de banda, gráficos, aceleradores neurais e motores multimédia processam IA, 3D e vídeo profissional." },
    "mac-pro-m2-ultra": { name: "Mac Pro", eyebrow: "APPLE SILICON. EXPANSÃO PCIE.", intro: "O último Mac Pro combina M2 Ultra com sete ranhuras de expansão para fluxos especializados numa icónica armação de aço inoxidável.", display: "M2 Ultra", primarySpecLabel: "CHIP", camera: "7 ranhuras", secondarySpecLabel: "PCIE", battery: "Rede elétrica", designTitle: "Feito para evoluir com o trabalho.", designBody: "A estrutura amovível permite acesso a 360 graus, rodas opcionais e espaço para hardware especializado.", cameraTitle: "Expansão integrada na arquitetura.", cameraBody: "Sete ranhuras, seis PCIe Gen 4, acrescentam I/O de áudio e vídeo, rede e armazenamento às ligações Thunderbolt.", secondarySectionKicker: "EXPANSÃO / 02", performanceTitle: "M2 Ultra à escala de workstation.", performanceBody: "CPU de 24 núcleos, GPU até 76 núcleos, Neural Engine de 32 núcleos e até 192 GB de memória unificada movem 3D, IA e 8K ProRes." },
  },
  es: {
    "macbook-air-m5": { name: "MacBook Air", eyebrow: "SUPERPOTENCIADO CON M5.", intro: "Portátil de 13 o 15 pulgadas increíblemente ligero, con M5, hasta 18 horas de batería y cámara Center Stage de 12 MP.", display: "13,6″ / 15,3″", camera: "Center Stage 12 MP", battery: "18 horas", designTitle: "Dos tamaños. Movilidad sin esfuerzo.", designBody: "La fina carcasa de aluminio ofrece cuatro acabados, MagSafe, dos puertos Thunderbolt 4 y diseño silencioso sin ventilador.", cameraTitle: "Liquid Retina. Siempre a punto.", cameraBody: "La pantalla Liquid Retina P3 se une a Center Stage de 12 MP, Vista Cenital, tres micrófonos y altavoces envolventes.", secondarySectionKicker: "PANTALLA / 02", performanceTitle: "M5 se encarga de todo.", performanceBody: "M5 acelera trabajo, creación, gráficos e IA en el dispositivo, con dos monitores externos y batería para todo el día." },
    "macbook-pro-m5": { name: "MacBook Pro", eyebrow: "POTENCIA PRO. HECHO PARA IA.", intro: "M5, M5 Pro o M5 Max, pantalla Liquid Retina XDR y hasta 24 horas de batería en formatos de 14 y 16 pulgadas.", display: "14,2″ / 16,2″ XDR", camera: "Center Stage 12 MP", battery: "24 horas", designTitle: "Un estudio portátil en dos tamaños.", designBody: "La carcasa de aluminio integra MagSafe 3, HDMI, SDXC, audio y tres puertos Thunderbolt para flujos profesionales.", cameraTitle: "Rango XDR. Claridad Center Stage.", cameraBody: "Liquid Retina XDR ofrece rango dinámico extremo y ProMotion; Center Stage de 12 MP añade Vista Cenital y videollamadas más nítidas.", secondarySectionKicker: "PANTALLA / 02", performanceTitle: "Elige M5, M5 Pro o M5 Max.", performanceBody: "CPU y GPU potentes, ray tracing por hardware, aceleradores neuronales y motores multimedia afrontan el trabajo profesional más exigente." },
    "imac-m4": { name: "iMac", eyebrow: "UN TODO EN UNO BRILLANTE.", intro: "M4, pantalla Retina 4.5K de 24 pulgadas, cámara Center Stage de 12 MP y gran sonido en un diseño excepcionalmente fino.", display: "24″ Retina 4.5K", camera: "Center Stage 12 MP", battery: "Corriente", designTitle: "Todo en una silueta vibrante.", designBody: "Con solo 11,5 mm, el iMac reúne ordenador y pantalla en siete colores con accesorios a juego.", cameraTitle: "Un lienzo para cada detalle.", cameraBody: "La pantalla Retina 4.5K ofrece 4480 × 2520 y color P3, junto con Center Stage, micrófonos de estudio y seis altavoces.", secondarySectionKicker: "PANTALLA / 02", performanceTitle: "M4 transforma el todo en uno.", performanceBody: "CPU, GPU y Neural Engine rápidos mueven creación, juegos, multitarea y Apple Intelligence con hasta 32 GB de memoria unificada." },
    "mac-mini-m6": { name: "Mac mini", eyebrow: "PEQUEÑO. MATÓN.", intro: "Sobremesa ultracompacto con M6 o M5 Pro, una potente plataforma para IA y puertos prácticos delante y detrás.", display: "M6 / M5 Pro", primarySpecLabel: "CHIP", camera: "Hasta 3", secondarySpecLabel: "PANTALLAS", battery: "Corriente", designTitle: "12,7 centímetros de posibilidades.", designBody: "La carcasa de aluminio sitúa USB-C y audio delante, con Thunderbolt, HDMI, Ethernet y corriente ordenados detrás.", cameraTitle: "Un centro flexible para tu espacio.", cameraBody: "Conecta pantallas de alta resolución, almacenamiento rápido, redes y accesorios mediante puertos frontales y traseros.", secondarySectionKicker: "CONEXIONES / 02", performanceTitle: "Velocidad M6. Escala M5 Pro.", performanceBody: "Elige M6 para tareas e IA rápidas o M5 Pro para código, multimedia y gráficos más exigentes en el mismo formato mínimo." },
    "mac-studio-m5": { name: "Mac Studio", eyebrow: "EL SOBREMESA PRO DEFINITIVO.", intro: "M5 Max o M5 Ultra, conexiones excepcionales e IA potente en el dispositivo dentro de una carcasa compacta.", display: "M5 Max / Ultra", primarySpecLabel: "CHIP", camera: "Hasta 8", secondarySpecLabel: "PANTALLAS", battery: "Corriente", designTitle: "Potencia de estudio. Formato de escritorio.", designBody: "La compacta carcasa de aluminio usa refrigeración avanzada para mantener cargas enormes en silencio.", cameraTitle: "Un estudio de conexiones.", cameraBody: "Thunderbolt 5, HDMI, Ethernet 10 Gb, USB, audio y SDXC conectan pantallas, almacenamiento, captura y redes rápidas.", secondarySectionKicker: "CONEXIONES / 02", performanceTitle: "M5 Max. M5 Ultra. Gran ambición.", performanceBody: "Memoria unificada de gran ancho de banda, gráficos, aceleradores neuronales y motores multimedia procesan IA, 3D y vídeo profesional." },
    "mac-pro-m2-ultra": { name: "Mac Pro", eyebrow: "APPLE SILICON. EXPANSIÓN PCIE.", intro: "El último Mac Pro combina M2 Ultra con siete ranuras de expansión para flujos especializados en su icónico armazón de acero inoxidable.", display: "M2 Ultra", primarySpecLabel: "CHIP", camera: "7 ranuras", secondarySpecLabel: "PCIE", battery: "Corriente", designTitle: "Hecho para evolucionar con el trabajo.", designBody: "La carcasa extraíble permite acceso de 360 grados, ruedas opcionales y espacio para hardware especializado.", cameraTitle: "La expansión forma parte de la arquitectura.", cameraBody: "Siete ranuras, seis PCIe Gen 4, añaden E/S de audio y vídeo, red y almacenamiento a una amplia conectividad Thunderbolt.", secondarySectionKicker: "EXPANSIÓN / 02", performanceTitle: "M2 Ultra a escala de workstation.", performanceBody: "CPU de 24 núcleos, GPU de hasta 76, Neural Engine de 32 y hasta 192 GB de memoria unificada impulsan 3D, IA y 8K ProRes." },
  },
  zh: {
    "macbook-air-m5": { name: "MacBook Air", eyebrow: "M5 芯片，强力加持。", intro: "轻盈的 13 英寸或 15 英寸笔记本，搭载 M5 芯片，电池续航最长 18 小时，并配备 1200 万像素人物居中摄像头。", display: "13.6″ / 15.3″", camera: "1200 万像素人物居中", battery: "18 小时", designTitle: "两种尺寸，轻装随行。", designBody: "轻薄铝金属机身提供四种外观，配备 MagSafe、两个雷雳 4 端口，并采用安静的无风扇设计。", cameraTitle: "Liquid Retina，出镜更出色。", cameraBody: "P3 广色域 Liquid Retina 显示屏，配合人物居中摄像头、桌上视角、三麦克风阵列和沉浸式扬声器。", secondarySectionKicker: "显示屏 / 02", performanceTitle: "M5，让一切举重若轻。", performanceBody: "M5 加速日常任务、创作、图形和设备端 AI，并支持两台外接显示器与全天续航。" },
    "macbook-pro-m5": { name: "MacBook Pro", eyebrow: "Pro 级性能，为 AI 而生。", intro: "M5、M5 Pro 或 M5 Max 芯片，Liquid Retina XDR 显示屏，以及最长 24 小时续航，提供 14 英寸和 16 英寸机型。", display: "14.2″ / 16.2″ XDR", camera: "1200 万像素人物居中", battery: "24 小时", designTitle: "两种尺寸，随身专业工作室。", designBody: "坚固铝金属机身集成 MagSafe 3、HDMI、SDXC、耳机插孔与三个雷雳端口。", cameraTitle: "XDR 动态范围，人物居中更清晰。", cameraBody: "Liquid Retina XDR 带来极致动态范围和 ProMotion，1200 万像素人物居中摄像头支持桌上视角。", secondarySectionKicker: "显示屏 / 02", performanceTitle: "M5、M5 Pro 或 M5 Max，任你选择。", performanceBody: "高性能 CPU 与 GPU、硬件光线追踪、神经网络加速器和媒体处理引擎应对专业工作。" },
    "imac-m4": { name: "iMac", eyebrow: "出彩的一体式电脑。", intro: "M4 芯片、24 英寸 4.5K Retina 显示屏、1200 万像素人物居中摄像头和充盈音效，尽纳纤薄设计。", display: "24″ 4.5K Retina", camera: "1200 万像素人物居中", battery: "交流供电", designTitle: "一体设计，七彩亮相。", designBody: "机身薄至 11.5 毫米，将电脑与显示屏融为一体，并有七种颜色及同色系配件。", cameraTitle: "每处细节，都有宽广画布。", cameraBody: "4.5K Retina 显示屏拥有 4480 × 2520 分辨率和 P3 广色域，另配录音室级麦克风和六扬声器系统。", secondarySectionKicker: "显示屏 / 02", performanceTitle: "M4，重塑一体式电脑。", performanceBody: "高速 CPU、GPU 和神经网络引擎推动创作、游戏、多任务与 Apple 智能，统一内存最高 32GB。" },
    "mac-mini-m6": { name: "Mac mini", eyebrow: "小身形，大身手。", intro: "超紧凑台式电脑搭载 M6 或 M5 Pro 芯片，为 AI 提供强大平台，前后端口实用丰富。", display: "M6 / M5 Pro", primarySpecLabel: "芯片", camera: "最多 3 台", secondarySpecLabel: "显示器", battery: "交流供电", designTitle: "12.7 厘米见方，潜力无限。", designBody: "紧凑铝金属机身在前方布置 USB-C 与音频接口，后方整齐容纳雷雳、HDMI、以太网和电源。", cameraTitle: "灵活连接，搭建你的工作空间。", cameraBody: "通过前后端口连接高分辨率显示器、高速存储、网络和各种配件。", secondarySectionKicker: "连接 / 02", performanceTitle: "M6 的速度，M5 Pro 的规模。", performanceBody: "M6 适合高速日常与 AI 工作，M5 Pro 则胜任更重的代码、媒体和图形任务。" },
    "mac-studio-m5": { name: "Mac Studio", eyebrow: "终极专业台式电脑。", intro: "M5 Max 或 M5 Ultra 芯片、丰富连接与强大设备端 AI，融入紧凑机身。", display: "M5 Max / Ultra", primarySpecLabel: "芯片", camera: "最多 8 台", secondarySpecLabel: "显示器", battery: "交流供电", designTitle: "工作室级实力，桌面级身形。", designBody: "紧凑铝金属机身采用先进散热系统，在多数显示器下方安静持续地处理巨量任务。", cameraTitle: "连接一整间工作室。", cameraBody: "雷雳 5、HDMI、万兆以太网、USB、音频和 SDXC 可连接显示器、存储、采集设备与高速网络。", secondarySectionKicker: "连接 / 02", performanceTitle: "M5 Max，M5 Ultra，雄心不设限。", performanceBody: "高带宽统一内存、强大图形、神经网络加速器和媒体引擎处理大型 AI 模型、3D 与专业视频。" },
    "mac-pro-m2-ultra": { name: "Mac Pro", eyebrow: "Apple 芯片，PCIe 扩展。", intro: "最后一代 Mac Pro 将 M2 Ultra 与七个扩展插槽结合，以经典不锈钢框架服务专业工作站流程。", display: "M2 Ultra", primarySpecLabel: "芯片", camera: "7 个插槽", secondarySpecLabel: "PCIE", battery: "交流供电", designTitle: "随工作流程而进化。", designBody: "可拆卸铝金属外壳与不锈钢框架提供 360 度内部访问、可选脚轮和专业硬件空间。", cameraTitle: "扩展能力，融入架构。", cameraBody: "七个插槽中有六个为 PCIe Gen 4，可扩展音视频 I/O、网络和存储，并配备丰富雷雳连接。", secondarySectionKicker: "扩展 / 02", performanceTitle: "工作站规模的 M2 Ultra。", performanceBody: "24 核 CPU、最高 76 核 GPU、32 核神经网络引擎与最高 192GB 统一内存，驱动 3D、AI 和 8K ProRes。" },
  },
  ja: {
    "macbook-air-m5": { name: "MacBook Air", eyebrow: "M5のパワーを、その手に。", intro: "驚くほど軽い13インチまたは15インチ。M5、最大18時間バッテリー、12MPセンターフレームカメラを搭載。", display: "13.6″ / 15.3″", camera: "12MPセンターフレーム", battery: "18時間", designTitle: "2つのサイズ。軽やかなモビリティ。", designBody: "薄いアルミニウムボディは4色。MagSafe、2つのThunderbolt 4ポート、静かなファンレス設計を備えます。", cameraTitle: "Liquid Retina。いつでも映える。", cameraBody: "P3対応Liquid Retina、センターフレーム、デスクビュー、3マイクアレイ、臨場感あるスピーカーを組み合わせました。", secondarySectionKicker: "ディスプレイ / 02", performanceTitle: "M5なら、軽々。", performanceBody: "M5が日常作業、制作、グラフィックス、デバイス上のAIを高速化。2台の外部ディスプレイと一日中使えるバッテリーにも対応します。" },
    "macbook-pro-m5": { name: "MacBook Pro", eyebrow: "プロのパワー。AIのために。", intro: "M5、M5 Pro、M5 Max、Liquid Retina XDR、最大24時間バッテリーを14インチと16インチに。", display: "14.2″ / 16.2″ XDR", camera: "12MPセンターフレーム", battery: "24時間", designTitle: "2つのサイズのポータブルスタジオ。", designBody: "丈夫なアルミニウムボディにMagSafe 3、HDMI、SDXC、ヘッドフォン、3つのThunderboltポートを統合。", cameraTitle: "XDRの幅。センターフレームの鮮明さ。", cameraBody: "Liquid Retina XDRが極めて広いダイナミックレンジとProMotionを、12MPカメラがデスクビューを届けます。", secondarySectionKicker: "ディスプレイ / 02", performanceTitle: "M5、M5 Pro、M5 Maxから選べます。", performanceBody: "高性能CPUとGPU、ハードウェアレイトレーシング、Neural Accelerator、メディアエンジンがプロの負荷に応えます。" },
    "imac-m4": { name: "iMac", eyebrow: "鮮やかなオールインワン。", intro: "M4、24インチ4.5K Retina、12MPセンターフレームカメラ、豊かなサウンドを驚くほど薄いデザインに。", display: "24″ 4.5K Retina", camera: "12MPセンターフレーム", battery: "電源接続", designTitle: "すべてを鮮やかなシルエットに。", designBody: "わずか11.5mmのボディにコンピュータとディスプレイを統合。7色と同色のアクセサリを用意しました。", cameraTitle: "細部まで広がるキャンバス。", cameraBody: "4480 × 2520の4.5K RetinaとP3カラーに、センターフレーム、スタジオ品質マイク、6スピーカーを組み合わせました。", secondarySectionKicker: "ディスプレイ / 02", performanceTitle: "M4がオールインワンを変える。", performanceBody: "高速なCPU、GPU、Neural Engineが制作、ゲーム、マルチタスク、Apple Intelligenceを最大32GBユニファイドメモリで動かします。" },
    "mac-mini-m6": { name: "Mac mini", eyebrow: "小さなボディ。大きな実力。", intro: "M6またはM5 Pro、パワフルなAI基盤、前後の便利なポートを備えた超コンパクトデスクトップ。", display: "M6 / M5 Pro", primarySpecLabel: "チップ", camera: "最大3台", secondarySpecLabel: "ディスプレイ", battery: "電源接続", designTitle: "12.7cm四方に広がる可能性。", designBody: "アルミニウムボディ前面にUSB-Cとオーディオ、背面にThunderbolt、HDMI、Ethernet、電源を整然と配置。", cameraTitle: "環境をつなぐ柔軟な中心。", cameraBody: "前後のポートで高解像度ディスプレイ、高速ストレージ、ネットワーク、アクセサリを接続できます。", secondarySectionKicker: "接続 / 02", performanceTitle: "M6の速さ。M5 Proのスケール。", performanceBody: "M6は日常とAIを高速に、M5 Proはより重いコード、メディア、グラフィックスを同じ小ささで処理します。" },
    "mac-studio-m5": { name: "Mac Studio", eyebrow: "究極のプロ向けデスクトップ。", intro: "M5 MaxまたはM5 Ultra、優れた接続性、強力なオンデバイスAIをコンパクトな筐体に。", display: "M5 Max / Ultra", primarySpecLabel: "チップ", camera: "最大8台", secondarySpecLabel: "ディスプレイ", battery: "電源接続", designTitle: "スタジオの力。机に収まる形。", designBody: "コンパクトなアルミニウムボディと先進的な熱設計が、大きな負荷を静かに持続します。", cameraTitle: "スタジオをつなぐポート。", cameraBody: "Thunderbolt 5、HDMI、10Gb Ethernet、USB、オーディオ、SDXCがディスプレイ、ストレージ、収録機器、高速ネットワークを結びます。", secondarySectionKicker: "接続 / 02", performanceTitle: "M5 Max。M5 Ultra。野心は最大。", performanceBody: "高帯域ユニファイドメモリ、強力なGPU、Neural Accelerator、メディアエンジンが大規模AI、3D、プロ映像を処理します。" },
    "mac-pro-m2-ultra": { name: "Mac Pro", eyebrow: "Appleシリコン。PCIe拡張。", intro: "最後のMac ProはM2 Ultraと7つの拡張スロットを象徴的なステンレススチールフレームに組み合わせました。", display: "M2 Ultra", primarySpecLabel: "チップ", camera: "7スロット", secondarySpecLabel: "PCIE", battery: "電源接続", designTitle: "仕事に合わせて変えられる設計。", designBody: "取り外せるアルミニウム筐体とフレームが360度アクセス、オプションのキャスター、専用ハードウェアの空間を提供します。", cameraTitle: "拡張性もアーキテクチャの一部。", cameraBody: "7スロット中6つがPCIe Gen 4。オーディオ／ビデオI/O、ネットワーク、ストレージを豊富なThunderbolt接続に追加できます。", secondarySectionKicker: "拡張 / 02", performanceTitle: "ワークステーション規模のM2 Ultra。", performanceBody: "24コアCPU、最大76コアGPU、32コアNeural Engine、最大192GBユニファイドメモリが3D、AI、8K ProResを動かします。" },
  },
};

export function getMacProductCopy(language: Language, model: MacModel) {
  return macProductCopy[language][model];
}
