import type { Language, Translation } from "./i18n";
import { getIphone16ProductCopy } from "./product-copy-16";
import { isIphone16Model, type Iphone17Model, type Model } from "./product-data";
import type { ProductCopy } from "./product-copy-types";

export type { ProductCopy } from "./product-copy-types";

type ProSeriesBase = Omit<ProductCopy, "name" | "display" | "battery">;

function proSeriesCopy(
  base: ProSeriesBase,
  sizes: {
    proDisplay: string;
    proBattery: string;
    maxDisplay: string;
    maxBattery: string;
  },
): Pick<Record<Iphone17Model, ProductCopy>, "17-pro" | "17-pro-max"> {
  return {
    "17-pro": {
      ...base,
      name: "iPhone 17 Pro",
      display: sizes.proDisplay,
      battery: sizes.proBattery,
    },
    "17-pro-max": {
      ...base,
      name: "iPhone 17 Pro Max",
      display: sizes.maxDisplay,
      battery: sizes.maxBattery,
    },
  };
}

const iphone17ProductCopy: Record<Language, Record<Iphone17Model, ProductCopy>> = {
  en: {
    ...proSeriesCopy(
      {
        eyebrow: "THE MOST POWERFUL IPHONE EVER.",
        intro: "An aluminum unibody, vapor-cooled A19 Pro, and three 48MP Fusion cameras with up to 8x optical-quality zoom.",
        camera: "3 × 48MP",
        designTitle: "Forged in aluminum. Built for Pro.",
        designBody: "A heat-forged aluminum unibody combines Ceramic Shield 2 on the front, Ceramic Shield on the back, and an integrated vapor chamber.",
        cameraTitle: "Three 48MP cameras. Eight pro lenses.",
        cameraBody: "Fusion Main, Ultra Wide, and Telephoto cover 13 mm to 200 mm, including an optical-quality 8x zoom.",
        performanceTitle: "A19 Pro. Cooled by vapor.",
        performanceBody: "A19 Pro works with an Apple-designed vapor chamber to deliver exceptional sustained performance for games, video, and Apple Intelligence.",
      },
      { proDisplay: "6.3″ ProMotion", proBattery: "33 hours", maxDisplay: "6.9″ ProMotion", maxBattery: "39 hours" },
    ),
    air: {
      name: "iPhone Air",
      eyebrow: "IMPOSSIBLY THIN.",
      intro: "A 5.6 mm titanium design, a 6.5-inch ProMotion display, and the power of A19 Pro.",
      display: "6.5″ ProMotion",
      camera: "48MP Fusion",
      battery: "27 hours",
      designTitle: "So this is what the future feels like.",
      designBody: "At just 5.6 mm and 165 grams, the Grade 5 titanium frame stays remarkably light while Ceramic Shield protects both sides.",
      cameraTitle: "Four lenses in your pocket.",
      cameraBody: "A 48MP Fusion Main camera delivers super-high-resolution photos, optical-quality 2x Telephoto, and 4K Dolby Vision video.",
      performanceTitle: "Pro power in a thin design.",
      performanceBody: "A19 Pro and its 5-core GPU bring pro-class performance to Apple’s thinnest iPhone, with all-day battery life.",
    },
    "17": {
      name: "iPhone 17",
      eyebrow: "MAGICHROMATIC.",
      intro: "A 6.3-inch ProMotion display, two 48MP Fusion cameras, and the fast, efficient A19 chip.",
      display: "6.3″ ProMotion",
      camera: "Dual 48MP",
      battery: "30 hours",
      designTitle: "Even more delightful. Even more durable.",
      designBody: "Contoured edges, thinner borders, and Ceramic Shield 2 frame a brighter 6.3-inch Super Retina XDR display.",
      cameraTitle: "All 48MP rear cameras.",
      cameraBody: "Fusion Main adds optical-quality 2x Telephoto, while Fusion Ultra Wide captures expansive scenes and detailed macro photos.",
      performanceTitle: "A19. Power player. Energy expert.",
      performanceBody: "The A19 chip powers Apple Intelligence, ProMotion, and advanced games while delivering up to 30 hours of video playback.",
    },
    "17e": {
      name: "iPhone 17e",
      eyebrow: "FEATURE STACKED. VALUE PACKED.",
      intro: "Ceramic Shield 2, the A19 chip, a 48MP Fusion camera, MagSafe, and 256GB to start.",
      display: "6.1″ XDR",
      camera: "48MP Fusion",
      battery: "26 hours",
      designTitle: "Designed to go the distance.",
      designBody: "A durable aluminum frame, Ceramic Shield 2, USB-C, and a seven-layer antireflective display coating are built for every day.",
      cameraTitle: "Perfect your portraits.",
      cameraBody: "The 48MP Fusion camera combines super-high resolution and an optical-quality 2x Telephoto in one versatile system.",
      performanceTitle: "Latest-generation A19.",
      performanceBody: "A19 handles Apple Intelligence, AAA games, and 4K streaming efficiently, with up to 26 hours of video playback.",
    },
  },
  vi: {
    ...proSeriesCopy(
      {
        eyebrow: "IPHONE MẠNH MẼ NHẤT TỪ TRƯỚC ĐẾN NAY.",
        intro: "Thiết kế nhôm nguyên khối, A19 Pro làm mát bằng buồng hơi và ba camera Fusion 48MP với zoom 8x chất lượng quang học.",
        camera: "3 × 48MP",
        designTitle: "Rèn từ nhôm. Sinh ra cho Pro.",
        designBody: "Khung nhôm nguyên khối rèn nhiệt kết hợp Ceramic Shield 2 ở mặt trước, Ceramic Shield ở mặt sau và buồng hơi tích hợp.",
        cameraTitle: "Ba camera 48MP. Tám ống kính Pro.",
        cameraBody: "Fusion Main, Ultra Wide và Telephoto phủ dải tiêu cự 13 mm đến 200 mm, bao gồm zoom 8x chất lượng quang học.",
        performanceTitle: "A19 Pro. Làm mát bằng buồng hơi.",
        performanceBody: "A19 Pro kết hợp buồng hơi do Apple thiết kế để duy trì hiệu năng vượt trội cho game, video và Apple Intelligence.",
      },
      { proDisplay: "6,3″ ProMotion", proBattery: "33 giờ", maxDisplay: "6,9″ ProMotion", maxBattery: "39 giờ" },
    ),
    air: {
      name: "iPhone Air",
      eyebrow: "MỎNG KHÔNG TƯỞNG.",
      intro: "Thiết kế titanium 5,6 mm, màn hình ProMotion 6,5 inch và sức mạnh của A19 Pro.",
      display: "6,5″ ProMotion",
      camera: "Fusion 48MP",
      battery: "27 giờ",
      designTitle: "Tương lai cho cảm giác như thế này.",
      designBody: "Chỉ mỏng 5,6 mm và nặng 165 gram, khung titanium Grade 5 vẫn bền chắc trong khi Ceramic Shield bảo vệ cả hai mặt.",
      cameraTitle: "Bốn tiêu cự trong túi bạn.",
      cameraBody: "Camera Chính Fusion 48MP chụp ảnh siêu phân giải, Telephoto 2x chất lượng quang học và video 4K Dolby Vision.",
      performanceTitle: "Sức mạnh Pro trong thiết kế mỏng.",
      performanceBody: "A19 Pro cùng GPU 5 lõi mang hiệu năng chuẩn Pro lên chiếc iPhone mỏng nhất, với pin dùng cả ngày.",
    },
    "17": {
      name: "iPhone 17",
      eyebrow: "RỰC RỠ SẮC MÀU.",
      intro: "Màn hình ProMotion 6,3 inch, hai camera Fusion 48MP và chip A19 nhanh, tiết kiệm điện.",
      display: "6,3″ ProMotion",
      camera: "Kép 48MP",
      battery: "30 giờ",
      designTitle: "Tuyệt hơn. Bền bỉ hơn.",
      designBody: "Các cạnh bo mềm mại, viền mỏng hơn và Ceramic Shield 2 bao quanh màn hình Super Retina XDR 6,3 inch sáng hơn.",
      cameraTitle: "Toàn bộ camera sau đều 48MP.",
      cameraBody: "Fusion Main có Telephoto 2x chất lượng quang học; Fusion Ultra Wide ghi lại cảnh rộng và ảnh macro giàu chi tiết.",
      performanceTitle: "A19. Mạnh mẽ và tiết kiệm.",
      performanceBody: "Chip A19 vận hành Apple Intelligence, ProMotion và game cao cấp, đồng thời phát video đến 30 giờ.",
    },
    "17e": {
      name: "iPhone 17e",
      eyebrow: "NHIỀU TÍNH NĂNG. GIÁ TRỊ VƯỢT TRỘI.",
      intro: "Ceramic Shield 2, chip A19, camera Fusion 48MP, MagSafe và dung lượng khởi điểm 256GB.",
      display: "6,1″ XDR",
      camera: "Fusion 48MP",
      battery: "26 giờ",
      designTitle: "Bền bỉ cho chặng đường dài.",
      designBody: "Khung nhôm bền chắc, Ceramic Shield 2, USB-C và lớp phủ chống phản chiếu bảy lớp sẵn sàng cho mỗi ngày.",
      cameraTitle: "Chân dung đẹp trọn vẹn.",
      cameraBody: "Camera Fusion 48MP kết hợp ảnh siêu phân giải và Telephoto 2x chất lượng quang học trong một hệ thống linh hoạt.",
      performanceTitle: "A19 thế hệ mới nhất.",
      performanceBody: "A19 xử lý hiệu quả Apple Intelligence, game AAA và nội dung 4K, với thời gian phát video đến 26 giờ.",
    },
  },
  pt: {
    ...proSeriesCopy(
      {
        eyebrow: "O IPHONE MAIS PODEROSO DE TODOS.",
        intro: "Estrutura unibody de alumínio, A19 Pro com câmara de vapor e três câmeras Fusion de 48 MP com zoom 8x de qualidade óptica.",
        camera: "3 × 48 MP",
        designTitle: "Forjado em alumínio. Feito para ser Pro.",
        designBody: "A estrutura unibody de alumínio forjado a quente combina Ceramic Shield 2 na frente, Ceramic Shield atrás e câmara de vapor integrada.",
        cameraTitle: "Três câmeras de 48 MP. Oito lentes Pro.",
        cameraBody: "Fusion principal, ultra-angular e teleobjetiva cobrem de 13 mm a 200 mm, incluindo zoom 8x de qualidade óptica.",
        performanceTitle: "A19 Pro. Resfriado a vapor.",
        performanceBody: "O A19 Pro e a câmara de vapor criada pela Apple mantêm desempenho excepcional em jogos, vídeo e Apple Intelligence.",
      },
      { proDisplay: "6,3″ ProMotion", proBattery: "33 horas", maxDisplay: "6,9″ ProMotion", maxBattery: "39 horas" },
    ),
    air: {
      name: "iPhone Air",
      eyebrow: "INCRIVELMENTE FINO.",
      intro: "Design em titânio de 5,6 mm, tela ProMotion de 6,5 polegadas e a potência do A19 Pro.",
      display: "6,5″ ProMotion",
      camera: "Fusion de 48 MP",
      battery: "27 horas",
      designTitle: "É assim que o futuro se sente.",
      designBody: "Com apenas 5,6 mm e 165 gramas, a estrutura em titânio grau 5 é muito leve e tem Ceramic Shield dos dois lados.",
      cameraTitle: "Quatro lentes no seu bolso.",
      cameraBody: "A câmera Fusion principal de 48 MP oferece alta resolução, teleobjetiva 2x com qualidade óptica e vídeo 4K Dolby Vision.",
      performanceTitle: "Potência Pro em um design fino.",
      performanceBody: "O A19 Pro e a GPU de 5 núcleos levam desempenho Pro ao iPhone mais fino, com bateria para o dia todo.",
    },
    "17": {
      name: "iPhone 17",
      eyebrow: "MAGICROMÁTICO.",
      intro: "Tela ProMotion de 6,3 polegadas, duas câmeras Fusion de 48 MP e o eficiente chip A19.",
      display: "6,3″ ProMotion",
      camera: "Dupla de 48 MP",
      battery: "30 horas",
      designTitle: "Mais encantador. Mais resistente.",
      designBody: "Bordas contornadas, margens mais finas e Ceramic Shield 2 envolvem a tela Super Retina XDR de 6,3 polegadas.",
      cameraTitle: "Todas as câmeras traseiras com 48 MP.",
      cameraBody: "A Fusion principal traz teleobjetiva 2x, enquanto a Fusion ultra-angular registra cenas amplas e macros detalhadas.",
      performanceTitle: "A19. Potência com eficiência.",
      performanceBody: "O A19 move Apple Intelligence, ProMotion e jogos avançados, com até 30 horas de reprodução de vídeo.",
    },
    "17e": {
      name: "iPhone 17e",
      eyebrow: "REPLETO DE RECURSOS. CHEIO DE VALOR.",
      intro: "Ceramic Shield 2, chip A19, câmera Fusion de 48 MP, MagSafe e 256 GB de capacidade inicial.",
      display: "6,1″ XDR",
      camera: "Fusion de 48 MP",
      battery: "26 horas",
      designTitle: "Feito para ir mais longe.",
      designBody: "Estrutura de alumínio, Ceramic Shield 2, USB-C e revestimento antirreflexo de sete camadas para todos os dias.",
      cameraTitle: "Retratos ainda melhores.",
      cameraBody: "A câmera Fusion de 48 MP une alta resolução e teleobjetiva 2x com qualidade óptica em um sistema versátil.",
      performanceTitle: "A19 de última geração.",
      performanceBody: "O A19 lida com Apple Intelligence, jogos AAA e streaming 4K, com até 26 horas de vídeo.",
    },
  },
  es: {
    ...proSeriesCopy(
      {
        eyebrow: "EL IPHONE MÁS POTENTE HASTA AHORA.",
        intro: "Diseño unibody de aluminio, A19 Pro con cámara de vapor y tres cámaras Fusion de 48 MP con zoom 8x de calidad óptica.",
        camera: "3 × 48 MP",
        designTitle: "Forjado en aluminio. Creado para ser Pro.",
        designBody: "El cuerpo unibody de aluminio forjado en caliente combina Ceramic Shield 2 delante, Ceramic Shield detrás y una cámara de vapor integrada.",
        cameraTitle: "Tres cámaras de 48 MP. Ocho lentes Pro.",
        cameraBody: "Fusion principal, ultra gran angular y teleobjetivo cubren de 13 mm a 200 mm, incluido zoom 8x de calidad óptica.",
        performanceTitle: "A19 Pro. Refrigerado por vapor.",
        performanceBody: "El A19 Pro y la cámara de vapor diseñada por Apple mantienen un rendimiento excepcional en juegos, vídeo y Apple Intelligence.",
      },
      { proDisplay: "6,3″ ProMotion", proBattery: "33 horas", maxDisplay: "6,9″ ProMotion", maxBattery: "39 horas" },
    ),
    air: {
      name: "iPhone Air",
      eyebrow: "INCREÍBLEMENTE FINO.",
      intro: "Diseño de titanio de 5,6 mm, pantalla ProMotion de 6,5 pulgadas y la potencia del A19 Pro.",
      display: "6,5″ ProMotion",
      camera: "Fusion de 48 MP",
      battery: "27 horas",
      designTitle: "Así se siente el futuro.",
      designBody: "Con solo 5,6 mm y 165 gramos, el marco de titanio de grado 5 es muy ligero y Ceramic Shield protege ambos lados.",
      cameraTitle: "Cuatro lentes en tu bolsillo.",
      cameraBody: "La cámara Fusion principal de 48 MP ofrece alta resolución, teleobjetivo 2x de calidad óptica y vídeo 4K Dolby Vision.",
      performanceTitle: "Potencia Pro en un diseño fino.",
      performanceBody: "El A19 Pro y su GPU de 5 núcleos llevan rendimiento Pro al iPhone más fino, con batería para todo el día.",
    },
    "17": {
      name: "iPhone 17",
      eyebrow: "MAGICROMÁTICO.",
      intro: "Pantalla ProMotion de 6,3 pulgadas, dos cámaras Fusion de 48 MP y el rápido y eficiente chip A19.",
      display: "6,3″ ProMotion",
      camera: "Doble de 48 MP",
      battery: "30 horas",
      designTitle: "Más encantador. Más resistente.",
      designBody: "Bordes contorneados, marcos más finos y Ceramic Shield 2 rodean la pantalla Super Retina XDR de 6,3 pulgadas.",
      cameraTitle: "Todas las cámaras traseras de 48 MP.",
      cameraBody: "La Fusion principal añade teleobjetivo 2x y la Fusion ultra gran angular captura escenas amplias y macros detallados.",
      performanceTitle: "A19. Potencia y eficiencia.",
      performanceBody: "El A19 impulsa Apple Intelligence, ProMotion y juegos avanzados, con hasta 30 horas de reproducción de vídeo.",
    },
    "17e": {
      name: "iPhone 17e",
      eyebrow: "LLENO DE FUNCIONES. REPLETO DE VALOR.",
      intro: "Ceramic Shield 2, chip A19, cámara Fusion de 48 MP, MagSafe y 256 GB de capacidad inicial.",
      display: "6,1″ XDR",
      camera: "Fusion de 48 MP",
      battery: "26 horas",
      designTitle: "Diseñado para llegar más lejos.",
      designBody: "Marco de aluminio, Ceramic Shield 2, USB-C y revestimiento antirreflejo de siete capas para el día a día.",
      cameraTitle: "Perfecciona tus retratos.",
      cameraBody: "La cámara Fusion de 48 MP combina alta resolución y teleobjetivo 2x de calidad óptica en un sistema versátil.",
      performanceTitle: "A19 de última generación.",
      performanceBody: "El A19 mueve Apple Intelligence, juegos AAA y streaming 4K, con hasta 26 horas de vídeo.",
    },
  },
  zh: {
    ...proSeriesCopy(
      {
        eyebrow: "迄今最强大的 IPHONE。",
        intro: "铝金属一体成型机身、蒸汽室散热 A19 Pro，以及支持光学品质 8 倍变焦的三颗 4800 万像素 Fusion 相机。",
        camera: "3 × 4800 万像素",
        designTitle: "铝金属锻造，为 Pro 而生。",
        designBody: "热锻铝金属一体成型机身，正面采用 Ceramic Shield 2，背面采用 Ceramic Shield，并集成蒸汽室。",
        cameraTitle: "三颗 4800 万像素相机，八个 Pro 级镜头。",
        cameraBody: "Fusion 主摄、超广角与长焦覆盖 13 毫米至 200 毫米焦段，并支持光学品质 8 倍变焦。",
        performanceTitle: "A19 Pro，蒸汽室散热。",
        performanceBody: "A19 Pro 与 Apple 设计的蒸汽室协同，为游戏、视频和 Apple 智能持续输出卓越性能。",
      },
      { proDisplay: "6.3″ ProMotion", proBattery: "33 小时", maxDisplay: "6.9″ ProMotion", maxBattery: "39 小时" },
    ),
    air: {
      name: "iPhone Air",
      eyebrow: "轻薄，难以置信。",
      intro: "5.6 毫米钛金属机身、6.5 英寸 ProMotion 显示屏，加上 A19 Pro 的强大性能。",
      display: "6.5″ ProMotion",
      camera: "4800 万像素 Fusion",
      battery: "27 小时",
      designTitle: "未来，原来是这种手感。",
      designBody: "机身仅 5.6 毫米、165 克，5 级钛金属边框轻盈坚固，前后均有 Ceramic Shield 防护。",
      cameraTitle: "四个焦段，尽在口袋。",
      cameraBody: "4800 万像素 Fusion 主摄可拍摄超高分辨率照片、光学品质 2 倍长焦和 4K 杜比视界视频。",
      performanceTitle: "轻薄机身，Pro 级实力。",
      performanceBody: "A19 Pro 和 5 核图形处理器为最纤薄的 iPhone 带来 Pro 级性能和全天候续航。",
    },
    "17": {
      name: "iPhone 17",
      eyebrow: "妙彩纷呈。",
      intro: "6.3 英寸 ProMotion 显示屏、两颗 4800 万像素 Fusion 相机，以及快速高效的 A19 芯片。",
      display: "6.3″ ProMotion",
      camera: "双 4800 万像素",
      battery: "30 小时",
      designTitle: "更讨喜，也更耐用。",
      designBody: "流畅边缘、更窄边框与 Ceramic Shield 2，共同围绕更明亮的 6.3 英寸超视网膜 XDR 显示屏。",
      cameraTitle: "后置相机，全部 4800 万像素。",
      cameraBody: "Fusion 主摄支持光学品质 2 倍长焦，Fusion 超广角则可拍摄开阔场景和细腻微距。",
      performanceTitle: "A19，强劲又高效。",
      performanceBody: "A19 驱动 Apple 智能、ProMotion 和大型游戏，并支持最长 30 小时视频播放。",
    },
    "17e": {
      name: "iPhone 17e",
      eyebrow: "功能满载，超值登场。",
      intro: "Ceramic Shield 2、A19 芯片、4800 万像素 Fusion 相机、MagSafe，256GB 起步。",
      display: "6.1″ XDR",
      camera: "4800 万像素 Fusion",
      battery: "26 小时",
      designTitle: "耐用设计，一路相伴。",
      designBody: "坚固铝金属边框、Ceramic Shield 2、USB-C 与七层抗反射涂层，轻松应对日常使用。",
      cameraTitle: "人像表现，更进一步。",
      cameraBody: "4800 万像素 Fusion 相机将超高分辨率与光学品质 2 倍长焦融于一个灵活系统。",
      performanceTitle: "新一代 A19。",
      performanceBody: "A19 高效处理 Apple 智能、大型游戏和 4K 串流，并支持最长 26 小时视频播放。",
    },
  },
  ja: {
    ...proSeriesCopy(
      {
        eyebrow: "史上最もパワフルな IPHONE。",
        intro: "アルミニウムユニボディ、ベイパーチャンバー冷却のA19 Pro、光学品質の8倍ズームに対応する3つの48MP Fusionカメラ。",
        camera: "3 × 48MP",
        designTitle: "アルミニウムから鍛造。Proのために。",
        designBody: "熱間鍛造アルミニウムのユニボディに、前面のCeramic Shield 2、背面のCeramic Shield、ベイパーチャンバーを統合しました。",
        cameraTitle: "3つの48MPカメラ。8つのProレンズ。",
        cameraBody: "Fusionメイン、超広角、望遠が13mmから200mmをカバーし、光学品質の8倍ズームにも対応します。",
        performanceTitle: "A19 Pro。ベイパーチャンバーで冷却。",
        performanceBody: "A19 ProとApple設計のベイパーチャンバーが、ゲーム、ビデオ、Apple Intelligenceで高い持続性能を発揮します。",
      },
      { proDisplay: "6.3″ ProMotion", proBattery: "33時間", maxDisplay: "6.9″ ProMotion", maxBattery: "39時間" },
    ),
    air: {
      name: "iPhone Air",
      eyebrow: "驚くほど薄い。",
      intro: "5.6mmのチタニウムボディ、6.5インチProMotionディスプレイ、A19 Proのパワー。",
      display: "6.5″ ProMotion",
      camera: "48MP Fusion",
      battery: "27時間",
      designTitle: "未来は、こんな手ざわり。",
      designBody: "わずか5.6mm、165グラム。Grade 5チタニウムフレームが軽さと強さを両立し、両面をCeramic Shieldが守ります。",
      cameraTitle: "4つの焦点距離をポケットに。",
      cameraBody: "48MP Fusionメインカメラで超高解像度写真、光学品質の2倍望遠、4K Dolby Visionビデオを撮影できます。",
      performanceTitle: "薄さの中に、Proのパワー。",
      performanceBody: "A19 Proと5コアGPUが最も薄いiPhoneにPro級の性能と一日中使えるバッテリーをもたらします。",
    },
    "17": {
      name: "iPhone 17",
      eyebrow: "色とりどりの魔法。",
      intro: "6.3インチProMotionディスプレイ、2つの48MP Fusionカメラ、高速で効率的なA19チップ。",
      display: "6.3″ ProMotion",
      camera: "デュアル48MP",
      battery: "30時間",
      designTitle: "もっと魅力的に。もっと頑丈に。",
      designBody: "なめらかなエッジ、より細いベゼル、Ceramic Shield 2が、明るい6.3インチSuper Retina XDRディスプレイを囲みます。",
      cameraTitle: "背面カメラはすべて48MP。",
      cameraBody: "Fusionメインは光学品質の2倍望遠に対応し、Fusion超広角は広大な景色や精細なマクロを捉えます。",
      performanceTitle: "A19。パワフルで効率的。",
      performanceBody: "A19がApple Intelligence、ProMotion、高度なゲームを動かし、最大30時間のビデオ再生を実現します。",
    },
    "17e": {
      name: "iPhone 17e",
      eyebrow: "機能満載。価値も満載。",
      intro: "Ceramic Shield 2、A19チップ、48MP Fusionカメラ、MagSafe、256GBからのストレージ。",
      display: "6.1″ XDR",
      camera: "48MP Fusion",
      battery: "26時間",
      designTitle: "長く使えるように設計。",
      designBody: "丈夫なアルミニウムフレーム、Ceramic Shield 2、USB-C、7層の反射防止コーティングを備えています。",
      cameraTitle: "ポートレートを美しく。",
      cameraBody: "48MP Fusionカメラが超高解像度と光学品質の2倍望遠を一つの柔軟なシステムに統合します。",
      performanceTitle: "最新世代のA19。",
      performanceBody: "A19がApple Intelligence、AAAゲーム、4Kストリーミングを効率よく処理し、最大26時間再生できます。",
    },
  },
};

export function getProductCopy(
  content: Translation,
  language: Language,
  model: Model,
): ProductCopy {
  if (model === "pro" || model === "duo") {
    return {
      ...content.models[model],
      designTitle: content.journey.designTitle[model],
      designBody: content.journey.designBody[model],
      cameraTitle: content.journey.cameraTitle[model],
      cameraBody: content.journey.cameraBody[model],
      performanceTitle: content.journey.performanceTitle,
      performanceBody: content.journey.performanceBody,
    };
  }

  if (isIphone16Model(model)) return getIphone16ProductCopy(language, model);
  return iphone17ProductCopy[language][model];
}
